import {useState,useEffect,useRef} from 'react';
import reference from '../src/reference.json';
const config=window.JIYU_THEME;
const catalogue=config.products;
export function variantFor(key,pack){return catalogue[key]?.variants?.find(v=>parseInt(v.option1,10)===pack+1)||catalogue[key]?.variants?.[pack]}
export function hasSellingPlan(key,pack){return Boolean(variantFor(key,pack)?.selling_plan_allocations?.length)}
for(const p of reference.products){const actual=catalogue[p.key];if(!actual?.variants?.length)continue;p.prices.forEach((price,pack)=>{const v=variantFor(p.key,pack);if(!v)return;price.price=v.price;price.compare_at_price=v.compare_at_price;price.sub_price=v.selling_plan_allocations?.[0]?.price||v.price;price.free_ship_otp=false})}
const endpoint=path=>(config.root||'/')+path;
async function api(path,body){const response=await fetch(endpoint(path),{credentials:'same-origin',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},...(body?{method:'POST',body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.description||result.message||'Unable to update your cart. Please try again.');return result}
function parse(cart){return cart.items.flatMap(item=>{for(const p of reference.products){const pack=(catalogue[p.key]?.variants||[]).findIndex(v=>v.id===item.variant_id);if(pack>=0)return [{key:p.key,pack,mode:item.selling_plan_allocation?'subscription':'onetime',price:item.final_price,qty:item.quantity,lineKey:item.key}]}return []})}
export function useShopifyCart(notify){const [cart,render]=useState([]);const [busy,setBusy]=useState(false);const current=useRef([]);const queue=useRef(Promise.resolve());const mounted=useRef(true);
useEffect(()=>{mounted.current=true;api('cart.js').then(c=>{if(mounted.current){current.current=parse(c);render(current.current)}}).catch(e=>notify(e.message));return()=>{mounted.current=false}},[]);
function update(action){queue.current=queue.current.catch(()=>{}).then(async()=>{setBusy(true);try{let existing=await api('cart.js');current.current=parse(existing);const next=typeof action==='function'?action(current.current):action;const desired=next.map(row=>{const v=variantFor(row.key,row.pack);if(!v?.id)throw new Error('This product is not configured in Shopify yet.');if(!v.available)throw new Error('This pack is currently sold out.');const plan=row.mode==='subscription'?v.selling_plan_allocations?.[0]?.selling_plan_id:undefined;if(row.mode==='subscription'&&!plan)throw new Error('Subscriptions are not available for this pack yet.');return {...row,id:v.id,plan}});
const signature=(id,plan)=>id+':'+(plan||'');const wanted=new Map(desired.map(r=>[signature(r.id,r.plan),r]));const updates={};for(const item of existing.items){if(!reference.products.some(p=>catalogue[p.key]?.variants?.some(v=>v.id===item.variant_id)))continue;const sig=signature(item.variant_id,item.selling_plan_allocation?.selling_plan?.id);const row=wanted.get(sig);updates[item.key]=row?.qty||0;if(row)wanted.delete(sig)}
if(Object.keys(updates).length)await api('cart/update.js',{updates});if(wanted.size)await api('cart/add.js',{items:Array.from(wanted.values()).map(r=>({id:r.id,quantity:r.qty,...(r.plan?{selling_plan:r.plan}:{})}))});const fresh=await api('cart.js');current.current=parse(fresh);render(current.current)}catch(e){notify(e.message);try{const fresh=await api('cart.js');current.current=parse(fresh);render(current.current)}catch{}}finally{setBusy(false)}});return queue.current}
async function checkout(){await queue.current;const latest=await api('cart.js');if(!latest.item_count){notify('Add an available product before checking out.');return}location.assign(endpoint('checkout'))}
return [cart,update,busy,checkout];}
