// Isolate each active overlay through its ancestors, including nested source markup.
export function initAccessibility(){
 let current=null,opener=null,isolated=[];
 const visible=el=>el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden'&&!el.closest('[hidden],[inert]');
 const release=()=>{isolated.forEach(el=>el.inert=false);isolated=[]};
 function sync(){release();const dialogs=[...document.querySelectorAll('[aria-modal="true"]')].filter(el=>el.getAttribute('aria-hidden')!=='true'&&visible(el));const next=dialogs.at(-1)||null;if(next!==current){const previous=current;current=next;if(next){document.dispatchEvent(new Event('jiyu:pause-videos'));document.querySelectorAll('video').forEach(v=>v.pause());opener=document.activeElement;if(!next.contains(document.activeElement))next.querySelector('button,a,input,summary')?.focus()}else if(previous&&opener?.isConnected)opener.focus()}
  if(!next)return;let node=next;while(node.parentElement){for(const sibling of node.parentElement.children){if(sibling!==node&&!sibling.inert&&!['SCRIPT','STYLE','LINK'].includes(sibling.tagName)){sibling.inert=true;isolated.push(sibling)}}node=node.parentElement;if(node===document.body)break}}
 const observer=new MutationObserver(sync);observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['aria-modal','class','hidden']});sync();
 function key(e){if(e.key==='Tab'&&current){const items=[...current.querySelectorAll('button,a[href],input,textarea,select,summary,iframe,[tabindex="0"]')].filter(el=>visible(el)&&!el.disabled&&el.tabIndex>=0);const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||!current.contains(document.activeElement))){e.preventDefault();e.stopPropagation();last?.focus()}else if(!e.shiftKey&&(document.activeElement===last||!current.contains(document.activeElement))){e.preventDefault();e.stopPropagation();first?.focus()}}
  const tab=e.target.closest('[role="tab"]');if(tab&&['ArrowRight','ArrowLeft','ArrowDown','ArrowUp','Home','End'].includes(e.key)){const group=tab.closest('[role="tablist"]')||tab.parentElement;const tabs=[...group.querySelectorAll('[role="tab"]')].filter(visible);let index=tabs.indexOf(tab);index=e.key==='Home'?0:e.key==='End'?tabs.length-1:(index+(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1)+tabs.length)%tabs.length;e.preventDefault();e.stopPropagation();tabs[index]?.focus();tabs[index]?.click()}}
 window.addEventListener('keydown',key,true);return()=>{observer.disconnect();release();window.removeEventListener('keydown',key,true)};
}
