import React, {useState,useEffect,useRef,memo} from 'react';
import Swiper from 'swiper';
import {Navigation,Pagination,A11y} from 'swiper/modules';
import data from './reference.json';
import detailData from './product-detail.json';
import {initAccessibility} from './accessibility.js';
import {reveal,initDetailMotion} from './motion.js';
import {initTranslation} from './translation.js';
import supportPages from './support-pages.json';
import './support-source.css';
import {initSupport} from './support.js';
import pages from './pages-reference.json';
import productPages from './product-pages.json';
import collection from './collection-reference.json';
import './collection.css';
import './products-source.css';
import './pages.css';
import ClinicianReviews from './ClinicianReviews.jsx';
import ClinicianSticker from './ClinicianSticker.jsx';
import CartContents from './CartContents.jsx';
import ProductGallery from './ProductGallery.jsx';
import AccountPanel,{SignInPage} from './AccountPanel.jsx';
import './account.css';
import CheckoutPage from './CheckoutPage.jsx';
import './checkout.css';
import {initReviews} from './reviews.js';
import {ReviewPhotos,ReviewForm} from './ReviewDialogs.jsx';
import './reviews.css';
import {initInlineVideos} from './inline-videos.js';
const pageRoutes={'/collections/all-products':'collection','/account/login':'signin','/checkout':'checkout','/pages/about-us':'about','/pages/loyalty-program':'loyalty','/pages/faq-page':'faq'};
const {media,products}=data;
const socialSection=data.outro.match(/<section\b[^>]*id="[^"]*instafeed[^"]*"[\s\S]*?<\/section>/)?.[0]||'';
const money=n=>'$'+(n/100).toFixed(2);
const names={toner:'renewal-rejuvenation-toner-pads',cream:'nad-anti-aging-moisturizing-cream',bundle:'test-complete-care-bundle'};
const productRoute=path=>Object.keys(names).find(k=>path==='/products/'+names[k]);
const canonicalPath=()=>location.pathname.replace(/^\/es(?=\/|$)/,'')||'/';
const currentPage=()=>pageRoutes[canonicalPath()]||(supportPages[canonicalPath()]?'support:'+canonicalPath():null)||(productRoute(canonicalPath())?'product-'+productRoute(canonicalPath()):canonicalPath()==='/'?'home':'notfound');
const descriptions={toner:"A breakthrough daily toner, packed with 8 Korean actives like Niacinamide, Snail Mucin & Peptides. JIYU’s toner pads visibly fade spots, refine texture, and boost elasticity — swipe daily or leave on for targeted treatment.",cream:'A breakthrough Korean daily moisturizing cream, powered by NAD+ and 8 other actives. Leave your skin firmer, plumper, smoother and deeply nourished.',bundle:'Two products. One routine. Toner Pads prep and treat. NAD+ Moisturizing Cream locks in hydration. Your complete Korean anti-aging routine in just 2 minutes.'};
const Raw=memo(({html})=><div dangerouslySetInnerHTML={{__html:html}}/>);
function Icon({name}){return <img src={'/assets/'+name+'.svg'} alt=""/>}
function Button({children,...props}){return <button className="j-button" {...props}>{children}</button>}
function Video({src,poster}){const ref=useRef(null);useEffect(()=>{const v=ref.current;let h;if(src.includes('.m3u8')&&window.Hls?.isSupported()){h=new window.Hls();h.loadSource(src);h.attachMedia(v);h.on(window.Hls.Events.MANIFEST_PARSED,()=>v.play().catch(()=>{}))}else{v.src=src;v.play().catch(()=>{})}return()=>{v.pause();h?.destroy()}},[src]);return <video ref={ref} poster={poster} controls playsInline/>}
export function App(){
 const [page,setPage]=useState(currentPage);
 useEffect(()=>initAccessibility(),[]);
 const [locale,setLocale]=useState(()=>location.pathname.match(/^\/es(?:\/|$)/)?'es':'en'),[languageOpen,setLanguageOpen]=useState(false);
 useEffect(()=>initTranslation(locale),[locale,page]);
 const localized=path=>locale==='es'?'/es'+(path==='/'?'':path):path;
 const chooseLanguage=next=>{setLanguageOpen(false);setLocale(next);history.replaceState(null,'',(next==='es'?'/es':'')+canonicalPath()+location.search+location.hash)};
 const [isMobile,setIsMobile]=useState(()=>matchMedia('(max-width:999px)').matches);
 useEffect(()=>{const q=matchMedia('(max-width:999px)');const change=()=>setIsMobile(q.matches);q.addEventListener('change',change);return()=>q.removeEventListener('change',change)},[]);
 const [headerHidden,setHeaderHidden]=useState(false);
 const navigationRef=useRef(null);
 useEffect(()=>{let last=window.scrollY,frame=0;const update=()=>{frame=0;const y=window.scrollY;const delta=y-last;if(y<130){setHeaderHidden(false);last=y}else if(Math.abs(delta)>5){setHeaderHidden(delta>0);last=y}};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};window.addEventListener('scroll',scroll,{passive:true});return()=>{window.removeEventListener('scroll',scroll);cancelAnimationFrame(frame)}},[]);

 function navigate(path){history.pushState(null,'',localized(path));setPage(currentPage());setMenu(false);setModal(null);setOffer(false);setLanguageOpen(false);window.scrollTo({top:0,behavior:'instant'})}
 useEffect(()=>{const pop=()=>{setLocale(location.pathname.match(/^\/es(?:\/|$)/)?'es':'en');setPage(currentPage());const restored=productRoute(canonicalPath())||Object.keys(names).find(k=>names[k]===new URLSearchParams(location.search).get('product'));if(restored){setKind(restored);setPhoto(0)}setMenu(false);setModal(null)};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);
 useEffect(()=>{document.title=page.startsWith('support:')?supportPages[page.slice(8)].title:page.startsWith('product-')?products.find(p=>p.key===page.slice(8)).title+' | JIYU':({collection:'All Products',signin:'Sign in',checkout:'Checkout',about:'About Us',loyalty:'Unfiltered Society',faq:'Frequently Asked Questions',home:'JIYU — Korean Skincare',notfound:'Page not found'})[page]+' | JIYU';},[page]);
 const [kind,setKind]=useState(()=>productRoute(canonicalPath())||Object.keys(names).find(k=>names[k]===new URLSearchParams(location.search).get('product'))||'bundle'),[pack,setPack]=useState(1),[mode,setMode]=useState('onetime'),[qty,setQty]=useState(1),[photo,setPhoto]=useState(0);
 const [shopCategory,setShopCategory]=useState('formulas'),[shopReview,setShopReview]=useState(0);
 const menuCloseTimer=useRef(null),shopTriggerRef=useRef(null);
 const keepShopOpen=()=>{clearTimeout(menuCloseTimer.current);setHeaderHidden(false);setMenu(true)};
 const leaveShop=()=>{clearTimeout(menuCloseTimer.current);menuCloseTimer.current=setTimeout(()=>{if(!document.querySelector('#j-shop-menu:hover,.j-shop-trigger:hover'))setMenu(false)},250)};
 const hoverShop=e=>{if(e.pointerType==='mouse'&&matchMedia('(hover:hover)').matches)keepShopOpen()};
 useEffect(()=>()=>clearTimeout(menuCloseTimer.current),[]);
 const [menu,setMenu]=useState(false),[drawer,setDrawer]=useState(false),[modal,setModal]=useState(null),[offer,setOffer]=useState(false),[offerHidden,setOfferHidden]=useState(false),[offerStep,setOfferStep]=useState(0),[discount,setDiscount]=useState(()=>localStorage.getItem('jiyu-discount')==='true'),[coupon,setCoupon]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{document.body.classList.toggle('j-mobile-shop-open',menu&&isMobile);if(menu&&isMobile)document.body.style.overflow='hidden';else if(!drawer&&!modal&&!offer)document.body.style.overflow='';return()=>document.body.classList.remove('j-mobile-shop-open')},[menu,isMobile,drawer,modal,offer]);
 const [cart,setCart]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('jiyu-assignment-cart')||'[]');return Array.isArray(saved)?saved.filter(x=>products.some(p=>p.key===x.key)&&Number.isInteger(x.pack)&&x.pack>=0&&x.pack<3&&['onetime','subscription'].includes(x.mode)&&Number.isFinite(x.price)&&x.price>0&&Number.isInteger(x.qty)&&x.qty>0).map(x=>({...x,qty:Math.min(99,x.qty)})):[]}catch{return []}});
 const dialogRef=useRef(null),triggerRef=useRef(null),ingredientRef=useRef(null),ingredientTriggerRef=useRef(null);
 const closeIngredient=()=>{const el=ingredientRef.current;if(el){el.classList.remove("active");el.setAttribute("aria-hidden","true");ingredientRef.current=null;document.body.style.overflow="";ingredientTriggerRef.current?.focus()}};
 const selectProduct=(key,dedicated=page.startsWith('product-'))=>{setKind(key);setPhoto(0);if(dedicated){setPage('product-'+key);history.pushState(null,'',localized('/products/'+names[key]))}else{history.replaceState(null,'',localized('/')+'?product='+names[key]+'#shop')}};
 const p=products.find(p=>p.key===kind),price=p.prices[pack],unit=mode==='subscription'?price.sub_price:price.price;
 const pd=detailData[kind],gallery=[pd.packImages[pack],...pd.images.slice(1)];
 const total=cart.reduce((a,x)=>a+x.price*x.qty,0),totalQty=cart.reduce((a,x)=>a+x.qty,0),discountAmount=discount?Math.round(total*.1):0;
 const shop=(key='bundle')=>{clearTimeout(menuCloseTimer.current);selectProduct(key,true);setMenu(false);setDrawer(false);setOffer(false);setOfferHidden(true);setModal(null);closeIngredient();requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'instant'}))};
 const scrollToShop=()=>requestAnimationFrame(()=>requestAnimationFrame(()=>document.getElementById('shop')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'})));
 const shopInline=(key=kind)=>{clearTimeout(menuCloseTimer.current);setMenu(false);setDrawer(false);setOffer(false);setModal(null);setOfferHidden(true);closeIngredient();setKind(key);setPhoto(0);if(page!=='home')setPage('home');history.pushState(null,'',localized('/')+'?product='+names[key]+'#shop');scrollToShop()};
 function add(key=kind){let prod=products.find(p=>p.key===key),opt=prod.prices[key===kind?pack:0],m=key===kind?mode:'onetime',q=key===kind?qty:1;let row={key,pack:key===kind?pack:0,mode:m,price:m==='subscription'?opt.sub_price:opt.price,qty:q};setCart(old=>{let i=old.findIndex(x=>x.key===row.key&&x.pack===row.pack&&x.mode===row.mode);return i<0?[...old,row]:old.map((x,j)=>j===i?{...x,qty:Math.min(99,x.qty+q)}:x)});setDrawer(true)}
 const change=(index,delta)=>setCart(old=>old.map((x,i)=>i===index?{...x,qty:Math.min(99,x.qty+delta)}:x).filter(x=>x.qty>0));
 useEffect(()=>{localStorage.setItem('jiyu-assignment-cart',JSON.stringify(cart))},[cart]);
 useEffect(()=>{if(!notice)return;let id=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(id)},[notice]);
 useEffect(()=>{let on=drawer||modal||offer;document.body.style.overflow=on?'hidden':'';if(on){document.querySelectorAll('video').forEach(v=>v.pause());setMenu(false);triggerRef.current=document.activeElement;requestAnimationFrame(()=>{if(dialogRef.current&&!dialogRef.current.contains(document.activeElement))dialogRef.current.querySelector('button,input')?.focus()})}else triggerRef.current?.focus?.();return()=>{document.body.style.overflow=''}},[drawer,modal,offer]);
 useEffect(()=>{function key(e){if(e.key==='Escape'){clearTimeout(menuCloseTimer.current);dismiss();setMenu(false);setLanguageOpen(false);if(shopTriggerRef.current?.getAttribute('aria-expanded')==='true')requestAnimationFrame(()=>shopTriggerRef.current?.focus());closeIngredient()}const focusRoot=dialogRef.current||ingredientRef.current;if(e.key==='Tab'&&focusRoot){let els=[...focusRoot.querySelectorAll('button,a,input,select,textarea,[tabindex="0"]')].filter(e=>e.offsetParent!==null);let first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[]);
 useEffect(()=>{
  if(!document.querySelector('main h1')){const heading=document.createElement('h1');heading.className='visually-hidden';heading.textContent=document.title.split('|')[0];document.querySelector('main')?.prepend(heading)}
  let sw=[];const cleanDetails=initDetailMotion();const cleanSupport=initSupport(setModal);const cleanVideos=initInlineVideos();const cleanReviews=initReviews(kind,setModal);
  document.querySelectorAll('.transformation-timeline').forEach(root=>{root.querySelector('.transformation-timeline__arrow--prev').disabled=true;root.querySelector('.transformation-timeline__arrow--next').disabled=false;root.querySelectorAll('[data-tt-card]').forEach((c,i)=>c.querySelector('button')?.setAttribute('aria-expanded',String(i===0)))});
  document.querySelectorAll('.ps__carousel').forEach(el=>sw.push(new Swiper(el,{modules:[Navigation,Pagination,A11y],slidesPerView:1,loop:false,navigation:{nextEl:el.querySelector('.ps__nav--next'),prevEl:el.querySelector('.ps__nav--prev')},pagination:{el:el.querySelector('.ps__pagination'),clickable:true}})));
  const ba=document.querySelector('.ba-results__carousel'),section=ba?.closest('section');
  if(ba){const s=new Swiper(ba,{modules:[Navigation,Pagination,A11y],slidesPerView:1.12,spaceBetween:16,breakpoints:{750:{slidesPerView:2.5,spaceBetween:30}},navigation:{nextEl:section.querySelector('.ba-results__nav--next'),prevEl:section.querySelector('.ba-results__nav--prev')},pagination:{el:section.querySelector('.ba-results__pagination'),clickable:true}});sw.push(s);section.querySelectorAll('button[aria-label^="View"]').forEach((b,i)=>b.onclick=()=>{s.slideTo(i);section.querySelectorAll('button[aria-label^="View"]').forEach((b,j)=>b.classList.toggle('ba-results__avatar--active',i===j))});s.on('slideChange',()=>section.querySelectorAll('button[aria-label^="View"]').forEach((b,i)=>b.classList.toggle('ba-results__avatar--active',i===s.activeIndex)))}
  document.querySelectorAll('[data-faq-tab]').forEach(b=>{let active=b.dataset.faqTab===({toner:'toner',cream:'moisturizer',bundle:'bundles'}[kind]);b.classList.toggle('is-active',active);b.setAttribute('aria-selected',String(active))});
  document.querySelectorAll('[data-faq-tab-panel]').forEach(x=>x.classList.toggle('is-active',x.dataset.faqTabPanel===({toner:'toner',cream:'moisturizer',bundle:'bundles'}[kind])));
  document.querySelectorAll('[data-jr-tab]').forEach(b=>{let active=b.dataset.jrTab===({toner:'tab_toner',cream:'tab_moisturizer',bundle:'tab_bundle'}[kind]);b.classList.toggle('is-active',active);b.setAttribute('aria-selected',String(active))});
  document.querySelectorAll('[data-jr-panel]').forEach(x=>x.classList.toggle('is-active',x.dataset.jrPanel===({toner:'tab_toner',cream:'tab_moisturizer',bundle:'tab_bundle'}[kind])));
  document.querySelectorAll('.faq-question').forEach((q,i)=>{q.tabIndex=0;q.setAttribute('role','button');q.setAttribute('aria-expanded','false');let answer=q.parentElement.querySelector('.faq-answer');answer.id='faq-answer-'+i;q.setAttribute('aria-controls',answer.id);answer.hidden=true;answer.style.maxHeight='0px'});
  const mobileVideos=document.querySelector('.video__slider');if(mobileVideos)sw.push(new Swiper(mobileVideos,{modules:[Navigation,Pagination,A11y],slidesPerView:1.25,spaceBetween:16,navigation:{nextEl:'.j-video-next',prevEl:'.j-video-prev'},pagination:{el:'.j-video-dots',clickable:true}}));
  function action(e){
   if(e.target.matches('.ing-spot__modal')){closeIngredient();return}if(!e.target.closest('.j-navigation'))setMenu(false);if(!e.target.closest('.j-language-wrap'))setLanguageOpen(false);
   const t=e.target.closest('a,button,[role="button"],[role="tab"]');if(!t)return;
   if(t.matches('[data-ct-tab]')){const root=t.closest('.comparison-table');root.querySelectorAll('[data-ct-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b===t));b.tabIndex=b===t?0:-1});root.querySelectorAll('[data-ct-panel]').forEach(p=>p.hidden=p.dataset.ctPanel!==t.dataset.ctTab);return}
   if(t.matches('.ct-tooltip__btn')){const tip=t.closest('.ct-tooltip'),open=tip.classList.toggle('is-open');t.setAttribute('aria-expanded',String(open));return}
   if(t.matches('[data-tt-tab],[data-tt-activate],.transformation-timeline__arrow')){const root=t.closest('.transformation-timeline'),cards=[...root.querySelectorAll('[data-tt-card]')];let i=cards.findIndex(c=>c.classList.contains('is-active'));if(t.matches('[data-tt-tab]'))i=Number(t.dataset.ttIndex);else if(t.matches('[data-tt-activate]'))i=Number(t.closest('[data-tt-card]').dataset.ttIndex);else i+=t.classList.contains('transformation-timeline__arrow--prev')?-1:1;i=Math.max(0,Math.min(cards.length-1,i));cards.forEach((c,j)=>{c.classList.toggle('is-active',j===i);c.querySelector('button')?.setAttribute('aria-expanded',String(j===i))});root.querySelectorAll('[data-tt-tab]').forEach((b,j)=>{b.classList.toggle('is-active',i===j);b.setAttribute('aria-current',String(i===j))});root.querySelector('.transformation-timeline__arrow--prev').disabled=i===0;root.querySelector('.transformation-timeline__arrow--next').disabled=i===cards.length-1;const track=root.querySelector('.transformation-timeline__track');track.scrollTo({left:cards[i].offsetLeft-track.offsetLeft,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});return}
   if(t.matches('[data-modal-target]')){closeIngredient();let m=document.getElementById(t.dataset.modalTarget);ingredientRef.current=m;ingredientTriggerRef.current=t;m?.querySelectorAll('img').forEach(img=>img.loading='eager');document.body.style.overflow='hidden';m?.classList.add('active');m?.setAttribute('aria-hidden','false');m?.setAttribute('role','dialog');m?.setAttribute('aria-modal','true');m?.querySelector('button')?.focus();return}
   if(t.matches('.ing-spot__modal-close')){closeIngredient();return}
   if(t.matches('.faq-question')){const answer=t.parentElement.querySelector('.faq-answer');const open=t.getAttribute('aria-expanded')!=='true';t.setAttribute('aria-expanded',String(open));t.parentElement.classList.toggle('active',open);t.classList.toggle('active',open);reveal(answer,open);return}
   if(t.matches('[data-faq-tab]')){let name=t.dataset.faqTab;let root=t.closest('.about-us-faq');root.querySelectorAll('[data-faq-tab]').forEach(b=>{let a=b===t;b.classList.toggle('is-active',a);b.setAttribute('aria-selected',String(a))});root.querySelectorAll('[data-faq-tab-panel]').forEach(x=>x.classList.toggle('is-active',x.dataset.faqTabPanel===name));return}
   if(t.matches('[data-jr-tab]')){let name=t.dataset.jrTab,root=t.closest('.jr-tabs');root.querySelectorAll('[data-jr-tab]').forEach(b=>{let a=b===t;b.classList.toggle('is-active',a);b.setAttribute('aria-selected',String(a))});root.querySelectorAll('[data-jr-panel]').forEach(x=>x.classList.toggle('is-active',x.dataset.jrPanel===name));return}
   if(t.matches('.video_card,.video_card_slider,[data-product-video]'))return;
   if(t.matches('.faq-tab[data-tab]')){const root=t.closest('.faq-section');root.querySelectorAll('.faq-tab').forEach(x=>{x.classList.toggle('active',x===t);x.setAttribute('aria-selected',String(x===t))});root.querySelectorAll('.faq-category').forEach(x=>{x.classList.toggle('active',x.id===t.dataset.tab);x.hidden=false;x.querySelectorAll('.faq-item').forEach(q=>q.hidden=false)});root.querySelector('.faq-search-input').value='';root.classList.remove('tabs-open');root.querySelector('.faq-filter-toggle')?.setAttribute('aria-expanded','false');root.querySelector('.j-faq-empty')?.remove();return}
   if(t.matches('.faq-filter-toggle')){const open=t.closest('.faq-section').classList.toggle('tabs-open');t.setAttribute('aria-expanded',String(open));return}
   if(t.matches('[data-skin-add-to-cart]')){add(({'44328294776911':'toner','44336908566607':'cream','44336912400463':'bundle'})[t.dataset.variantId]||'bundle');return}
   if(t.matches('[data-shop-product]')){shop(t.dataset.shopProduct);return}
   if(t.matches('.rivo-slider-nav')){const slider=document.querySelector('.rivo-slider-track');slider?.scrollBy({left:(t.classList.contains('rivo-slider-nav--prev')?-1:1)*slider.clientWidth*.8,behavior:'smooth'});return}
   if(t.matches('.rivo-card,.rivo-earn-card,.rivo-cards-card')){setModal({title:'Account',account:true});return}
   if(t.tagName==='A'){
    let h=t.getAttribute('href')||'';h=h.replace(/^\/es(?=\/|$)/,'')||'/';if(h.startsWith('https://www.jiyuskin.com/'))h=h.replace('https://www.jiyuskin.com','');if(supportPages[h.split('#')[0]]){e.preventDefault();const url=new URL(h,location.origin);if(url.pathname===location.pathname&&url.hash){document.getElementById(url.hash.slice(1))?.scrollIntoView({behavior:'smooth'})}else navigate(url.pathname+url.hash);return}
    if(pageRoutes[h]){e.preventDefault();navigate(h);return}
    if(h==='#rivo'){e.preventDefault();setModal({title:'Account',account:true});return}
    if(h==='#featured-product-anchor'||h==='#shop'||h==='#hps-buy'){e.preventDefault();if(page==='home')document.getElementById('shop')?.scrollIntoView({behavior:'smooth'});else{navigate('/');requestAnimationFrame(()=>document.getElementById('shop')?.scrollIntoView({behavior:'smooth'}))}return}if(h.startsWith('/collections')){e.preventDefault();navigate('/collections/all-products');return}
    if(h.startsWith('http')){t.target='_blank';t.rel='noopener noreferrer';return}
    if(h.startsWith('/?product=')){e.preventDefault();const requested=new URL(h,location.origin).searchParams.get('product');shopInline(Object.keys(names).find(k=>names[k]===requested)||'bundle');return}if(h.includes('product')||h==='#shop'){e.preventDefault();shop(h.includes('toner')?'toner':h.includes('nad-anti')?'cream':'bundle');return}
    if(h.includes('faq')){e.preventDefault();navigate('/pages/faq-page');return}
    if(h==='#MainContent'){e.preventDefault();document.getElementById('MainContent')?.focus();document.getElementById('MainContent')?.scrollIntoView();return}if(h==='/'){e.preventDefault();navigate('/');return}
    if(h.startsWith('/pages/')||h.startsWith('/blogs/')||h.startsWith('/apps/')||h.includes('customer_authentication')){e.preventDefault();setModal({title:t.textContent.trim(),text:'This is an educational JIYU storefront recreation. Live customer accounts, policies and support are available on the original JIYU website.',link:new URL(h,'https://www.jiyuskin.com').href});return}
    if(h.startsWith('http')){t.target='_blank';t.rel='noopener noreferrer'}
   }
  }
  function search(e){if(!e.target.matches('.faq-search-input'))return;const root=e.target.closest('.faq-section'),term=e.target.value.toLowerCase().trim();let count=0;root.querySelectorAll('.faq-category').forEach((cat,i)=>{let hits=0;cat.querySelectorAll('.faq-item').forEach(item=>{const match=!term||item.textContent.toLowerCase().includes(term);item.hidden=!match;if(match)hits++});cat.classList.toggle('active',term?hits>0:i===0);count+=hits});root.querySelector('.j-faq-empty')?.remove();if(!count){const empty=document.createElement('p');empty.className='j-faq-empty';empty.setAttribute('role','status');empty.textContent='No results found. Try another search.';root.querySelector('.faq-content-area').append(empty)}}
  document.querySelectorAll('.rivo-card,.rivo-earn-card,.rivo-cards-card').forEach(el=>{el.tabIndex=0;el.setAttribute('role','button')});
  document.querySelectorAll('.faq-tab[data-tab]').forEach(t=>{t.setAttribute('role','tab');t.tabIndex=0;t.setAttribute('aria-selected',String(t.classList.contains('active')))});
  document.querySelectorAll('.faq-filter-toggle').forEach(t=>t.setAttribute('aria-expanded','false'));
  document.querySelectorAll('.skin-concerns-slider').forEach(el=>sw.push(new Swiper(el,{slidesPerView:1.15,spaceBetween:20,breakpoints:{750:{slidesPerView:3}}})));
  const rewards=document.querySelector('.rivo-slider-track');const updateRewards=()=>{const prev=document.querySelector('.rivo-slider-nav--prev'),next=document.querySelector('.rivo-slider-nav--next');if(prev)prev.disabled=rewards.scrollLeft<=1;if(next)next.disabled=rewards.scrollLeft+rewards.clientWidth>=rewards.scrollWidth-2};if(rewards){rewards.addEventListener('scroll',updateRewards);updateRewards()}
  function submit(e){if(e.target.matches('.j-referral-form')){e.preventDefault();e.target.querySelector('.j-referral-result').textContent='Your demo referral link: '+location.origin+'/?ref=unfiltered-demo';return}if(e.target.closest('footer')){e.preventDefault();setDiscount(true);localStorage.setItem('jiyu-discount','true');setNotice('Your demo welcome code is GLOW10 — 10% off your bag.');e.target.reset()}}
  function keyboard(e){if((e.key==='Enter'||e.key===' ')&&e.target.matches('.faq-question,.faq-tab[data-tab],[data-modal-target],.rivo-card,.rivo-earn-card,.rivo-cards-card')){e.preventDefault();e.target.click()}}
  document.addEventListener('input',search);document.addEventListener('click',action);document.addEventListener('submit',submit);document.addEventListener('keydown',keyboard);
  const requested=new URLSearchParams(location.search).get('product')||location.pathname.split('/products/')[1]?.split('/')[0];if(requested&&page==='home'){let found=Object.keys(names).find(k=>names[k]===requested);if(found){setKind(found);setOfferHidden(true);scrollToShop()}}
  return()=>{cleanDetails();cleanSupport();cleanReviews();cleanVideos();sw.forEach(s=>s.destroy());rewards?.removeEventListener('scroll',updateRewards);document.removeEventListener('input',search);document.removeEventListener('click',action);document.removeEventListener('submit',submit);document.removeEventListener('keydown',keyboard)};
 },[page,locale,kind]);
 const closingRef=useRef(false);
 const dismiss=()=>{if(closingRef.current)return;const panel=dialogRef.current,backdrop=panel?.parentElement;const finish=()=>{setModal(null);setDrawer(false);setOffer(false);closingRef.current=false};if(!panel||matchMedia('(prefers-reduced-motion:reduce)').matches){finish();return}closingRef.current=true;const drawerPanel=panel.classList.contains('j-drawer'),accountPanel=panel.classList.contains('j-account-dialog');const duration=drawerPanel?200:accountPanel?300:150;panel.style.pointerEvents='none';const animation=panel.animate(drawerPanel||accountPanel?[{transform:'translateX(0)'},{transform:accountPanel?'translateX(-105%)':'translateX(100%)'}]:[{opacity:1},{opacity:0}],{duration,easing:'ease',fill:'forwards'});backdrop.animate([{backgroundColor:getComputedStyle(backdrop).backgroundColor},{backgroundColor:'transparent'}],{duration,fill:'forwards'});animation.finished.then(finish,finish)};
 if(page==='checkout')return <CheckoutPage cart={cart} discount={discount} setDiscount={v=>{setDiscount(v);localStorage.setItem('jiyu-discount',String(v))}} home={()=>navigate('/')} returnCart={()=>{navigate('/');setDrawer(true)}} signIn={()=>navigate('/account/login')}/>;
 if(page==='signin')return <SignInPage home={()=>navigate('/')}/>;
 return <>
  <a className="j-skip" href="#MainContent">Skip to content</a>
  <div className="j-promo"><img src="/assets/1263439a4626ed14.svg" alt="Special offer"/> SAVE UP TO 45%! <button onClick={()=>page==='home'?document.getElementById('shop')?.scrollIntoView({behavior:'smooth'}):shop()}>Shop Now</button></div>
  <div ref={navigationRef} role={menu&&isMobile?'dialog':undefined} aria-modal={menu&&isMobile?'true':undefined} aria-label={menu&&isMobile?'Shop navigation':undefined} className={"j-navigation"+(headerHidden&&!menu?" j-navigation-hidden":"")} onFocusCapture={()=>setHeaderHidden(false)} onMouseLeave={leaveShop}>
  <header className={"j-header"+(page!=="home"?" j-header-page":"")}>
   <button className="j-mobile-menu j-icon" aria-label="Menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Icon name={menu?"mobile-menu-close":"menu"}/></button>
   <a href="/" className="j-logo"><img src={media.logo} alt="JIYU"/></a>
   <nav><button ref={shopTriggerRef} className="j-shop-trigger" onPointerEnter={hoverShop} onClick={keepShopOpen} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();keepShopOpen();requestAnimationFrame(()=>document.querySelector('#j-shop-menu button')?.focus())}}} aria-expanded={menu} aria-controls="j-shop-menu">SHOP</button>{[['/pages/about-us','ABOUT US'],['/pages/loyalty-program','UNFILTERED SOCIETY'],['/pages/faq-page','FAQS']].map(([href,title])=><a key={href} href={href} onMouseEnter={()=>setMenu(false)} aria-current={pageRoutes[href]===page?'page':undefined}>{title}</a>)}</nav>
   <div className="j-header-actions"><div className="j-language-wrap" data-no-translate=""><button className="j-language" aria-label="Language" aria-expanded={languageOpen} aria-controls="j-language-list" onClick={()=>setLanguageOpen(!languageOpen)}>{locale.toUpperCase()}<span aria-hidden="true">⌄</span></button>{languageOpen&&<div id="j-language-list" className="j-language-list">{[['en','English'],['es','Español']].map(([code,label])=><button key={code} lang={code} aria-current={code===locale?'true':undefined} onClick={()=>chooseLanguage(code)}><img src="/assets/language-check.svg" alt="" style={{visibility:code===locale?'visible':'hidden'}}/>{label}</button>)}</div>}</div><button className="j-icon" aria-label="Account" onClick={()=>setModal({title:'Account',account:true})}><Icon name="account"/></button><button className="j-icon" aria-label={'Cart'+(totalQty?' ('+totalQty+')':'')} onClick={()=>setDrawer(true)}><Icon name="cart"/>{totalQty>0&&<span className="j-count">{totalQty}</span>}</button></div>
  </header>
  {menu&&<div id="j-shop-menu" className="j-mega j-shop-dropdown" onMouseEnter={keepShopOpen} onMouseLeave={leaveShop} onFocusCapture={()=>clearTimeout(menuCloseTimer.current)} onBlurCapture={e=>{if(e.relatedTarget&&!e.currentTarget.contains(e.relatedTarget)&&e.relatedTarget!==shopTriggerRef.current)setMenu(false)}} style={{top:document.querySelector('.j-header')?.getBoundingClientRect().bottom||129}}>
   <div className="j-shop-menu-layout">
    <aside className="j-shop-menu-sidebar"><div className="j-shop-categories" role="tablist" aria-label="Shop categories">{[['formulas','Formulas'],['bundles','Bundle & Save']].map(([key,label])=><button key={key} role="tab" aria-selected={shopCategory===key} aria-controls="j-shop-products" className={shopCategory===key?'active':''} onPointerEnter={e=>{if(e.pointerType==='mouse')setShopCategory(key)}} onClick={()=>setShopCategory(key)}>{label}</button>)}<a className="j-shop-all-link" href="/collections/all-products">Shop All</a></div>
     <div className="j-shop-testimonial"><a href={'/products/'+names[['bundle','toner','cream'][shopReview]]}><p>{['"I love these products. I have seen a change in my skin while using them. My face is less wrinkled and shines and just looks healthy. I also love that this is a female owned company!"','"They gently exfoliate without irritating my skin and leave my face feeling clean, smooth, and refreshed. I’ve noticed brighter skin and a more even tone with regular use. Super convenient, soothing, and perfect for daily skincare—no wonder they went viral!"','"I love this moisturizer!!! It absorbs quickly, it’s not greasy, and leaves my face feeling hydrated all day. I use it as part of my morning routine."'][shopReview]}</p><div><img src={media[['bundlePhoto','tonerPhoto','creamPhoto'][shopReview]]} alt=""/><strong>{['Kim I.','Maria M.','Julia P.'][shopReview]}</strong></div><span>{products.find(p=>p.key===['bundle','toner','cream'][shopReview]).title}</span></a><div className="j-shop-review-controls"><button aria-label="Previous menu review" disabled={shopReview===0} onClick={()=>setShopReview(shopReview-1)}><img src="/assets/shop-review-prev.svg" alt=""/></button>{[0,1,2].map(i=><button key={i} className={'j-shop-review-dot'+(shopReview===i?' active':'')} aria-label={'Menu review '+(i+1)} aria-pressed={shopReview===i} onClick={()=>setShopReview(i)}/>)}<button aria-label="Next menu review" disabled={shopReview===2} onClick={()=>setShopReview(shopReview+1)}><img src="/assets/shop-review-next.svg" alt=""/></button></div></div>
    </aside>
    <div id="j-shop-products" className="j-shop-menu-products" role="tabpanel" aria-label={shopCategory==='formulas'?'Formulas':shopCategory==='bundles'?'Bundle & Save':'Shop All'}>{products.filter(x=>isMobile||shopCategory==='all'||(shopCategory==='bundles'?x.key==='bundle':x.key!=='bundle')).map(x=><a href={'/products/'+names[x.key]} key={x.key} className={'j-shop-menu-card j-shop-menu-card-'+x.key}><img src={media[x.key]} alt=""/><h3>{x.key==='bundle'?'Anti-Aging Glow-Up System':x.title}</h3><p>{({toner:'Fade dark spots, smooth texture, and hydrate — daily or as a 15-min mask.',cream:'Powered by NAD+ to boost collagen, restore firmness, and fight visible aging.',bundle:'2 products. 2 minutes. Your entire skincare routine, replaced.'})[x.key]}</p><span className="j-button">BUY NOW</span></a>)}</div>
   </div>
   <div className="j-mobile-pages"><a href="/collections/all-products">SHOP ALL</a><a href="/pages/about-us">ABOUT US</a><a href="/pages/loyalty-program">UNFILTERED SOCIETY</a><a href="/pages/faq-page">FAQS</a><details className="j-mobile-language" data-no-translate=""><summary>Language: {locale==='es'?'Español':'English'}</summary>{[['en','English'],['es','Español']].map(([code,label])=><button key={code} aria-current={code===locale?'true':undefined} onClick={()=>chooseLanguage(code)}>{label}</button>)}</details></div>
  </div>}
  </div>
  <main id="MainContent" tabIndex={-1} className={page.startsWith('product-')?'j-product-page':''}>{page!=='home'&&!page.startsWith('product-')?<div className={"j-page j-page-"+page+(page.startsWith('support:')?' j-support-page':'')} data-support-path={page.startsWith('support:')?page.slice(8):undefined}><Raw key={page} html={page==='collection'?collection.html:page==='notfound'?'<section class="j-not-found"><p>404</p><h1>Page not found</h1><a class="j-button" href="/">Continue shopping</a></section>':page.startsWith('support:')?supportPages[page.slice(8)].html:pages[page]}/><Raw html={pages.footer}/></div>:<>{page==='home'&&<Raw html={data.intro}/>}
   <section id="shop" className="j-shop j-pdp">
    <ProductGallery mobile={isMobile} gallery={gallery} title={p.title} kind={kind} photo={photo} setPhoto={setPhoto} open={i=>setModal({title:p.title,image:gallery[i],gallery,index:i})}/>
    <div className="j-buy">
     <button className="j-rating" onClick={()=>{const tab=document.querySelector('[data-jr-tab="'+({toner:'tab_toner',cream:'tab_moisturizer',bundle:'tab_bundle'}[kind])+'"]');tab?.click();document.querySelector('.jm-review-widget,.jr-tabs')?.scrollIntoView({behavior:'smooth'})}}><span className="j-pdp-stars" aria-hidden="true">{[0,1,2,3,4].map(i=><span key={i} className={"jdgm-star "+(i===4?"jdgm--half":"jdgm--on")}/>)}</span><span className="j-review-count">{kind==='toner'?'12441':kind==='cream'?'967':'1832'} reviews</span></button>
     {page.startsWith('product-')?<h1>{p.title}</h1>:<h2>{p.title}</h2>}
     <div className="j-description" dangerouslySetInnerHTML={{__html:pd.descriptionHtml}}/>
     <ul className="j-features">{pd.features.map(f=><li key={f.text}><img src={f.image} alt=""/><span>{f.text}</span></li>)}</ul>
     {page.startsWith('product-')&&<ClinicianSticker key={kind} kind={kind} visible quant/>}
     <div className="j-product-tabs">{products.filter(x=>kind==='bundle'||x.key===kind||x.key==='bundle').map(x=><button key={x.key} className={kind===x.key?'selected':''} onClick={()=>selectProduct(x.key)}><img src={media[x.key]} alt=""/>{x.key==='toner'?'Toner':x.key==='cream'?'Moisturizer':'Bundle & Save'}</button>)}</div>
     <fieldset className="j-packs"><legend className="visually-hidden">Pack size</legend>{p.prices.map((x,i)=><label className={pack===i?'selected':''} key={i}><input type="radio" name="pack" checked={pack===i} onChange={()=>{setPack(i);setPhoto(0)}}/>{i>0&&<span className="j-badge">{i===1?'Most Popular':'Best Deal'}</span>}<strong>{i+1} {i===0?'Jar':'Jars'}{kind==='bundle'?' Each':''}</strong>{i>0&&<small>Save up to {money((x.compare_at_price||x.price)-x.sub_price)}</small>}</label>)}</fieldset>
     <fieldset className="j-modes"><legend className="visually-hidden">Purchase type</legend>
      <label className={mode==='subscription'?'selected':''}><div className="j-mode-banner">Most Popular: Save up to <strong>{kind==='bundle'?'45':'40'}%</strong></div><div className="j-mode-title"><input type="radio" name="mode" checked={mode==='subscription'} onChange={()=>setMode('subscription')}/><strong>Subscribe & Save</strong><span><s>{money(price.compare_at_price||price.price)}</s> <b>{money(price.sub_price)}</b><small>{price.per_day_sub_money} per day</small></span></div><ul><li>Lock in {Math.round((1-price.sub_price/(price.compare_at_price||price.price))*100)}% off forever</li><li><b>FREE</b> shipping forever</li><li>Earn <b>{Math.round(price.sub_price*qty/100*2)+100}</b> points</li><li><b>2x</b> points on every order</li><li>Cancel, pause or modify <b>any time</b></li></ul><p className="j-delivery j-sub-delivery">{price.plan_name.replace('*','')} · {money(price.sub_price)} each delivery</p></label>
      <label className={mode==='onetime'?'selected':''}><div className="j-mode-title"><input type="radio" name="mode" checked={mode==='onetime'} onChange={()=>setMode('onetime')}/><strong>One Time Purchase</strong><span>{price.compare_at_price&&<s>{money(price.compare_at_price)}</s>} <b>{money(price.price)}</b><small>{price.per_day_otp_money} per day</small></span></div>{price.free_ship_otp&&<ul><li><b>FREE</b> shipping</li></ul>}</label>
     </fieldset>
     <div className="j-add"><div className="j-quantity"><button aria-label="Decrease quantity" onClick={()=>setQty(Math.max(1,qty-1))}><img src="/assets/pdp-minus.svg" alt=""/></button><input aria-label="Quantity" type="number" min="1" max="99" value={qty} onChange={e=>setQty(Math.min(99,Math.max(1,Number(e.target.value)||1)))}/><button aria-label="Increase quantity" onClick={()=>setQty(Math.min(99,qty+1))}><img src="/assets/pdp-plus.svg" alt=""/></button></div><Button onClick={()=>add()}>ADD TO CART</Button></div>
     <div className="j-guarantee"><img src={detailData.guarantee} alt="90-day guarantee"/><p><strong>Try it risk-free for 90 days.</strong> If you’re not totally in love with your results, we will refund you 100%</p></div>
     <div className="j-clean" aria-label="Product standards"><div>{['CRUELTY FREE','VEGAN','PARABEN FREE','SULFATE FREE','PHTHALATE FREE','MINERAL OIL FREE','ALCOHOL FREE','FORMALDEHYDE FREE','EDTA FREE','HYDROQUINONE FREE','TALC FREE','SYNTHETIC DYE FREE','CLEAN FORMULA','DERMATOLOGIST TESTED'].map(t=><span key={t}>{t}</span>)}</div></div>
     <div className="j-product-videos" aria-label="Customer review videos">{pd.videos.map((v,i)=><button key={v.src} aria-label={'Play product review video '+(i+1)} data-product-video="" data-video-src={v.src}><img className="j-review-poster" src={v.poster} alt={'Customer video review '+(i+1)} loading="lazy"/><img className="j-review-play" src="/assets/pdp-play.svg" alt=""/></button>)}</div>
     <div key={kind} className="j-product-details">{pd.details.map((d,i)=><details key={d.title} className="j-detail" open={i===0}><summary aria-expanded={i===0}>{d.title}<img className="j-detail-plus" src="/assets/pdp-plus.svg" alt=""/><img className="j-detail-minus" src="/assets/pdp-minus.svg" alt=""/></summary><div className="j-detail-body"><div className="j-detail-content" dangerouslySetInnerHTML={{__html:d.html}}/>{d.fullIngredients&&<button className="j-ingredients-link" onClick={()=>setModal({title:'Full ingredients',text:d.fullIngredients})}>See All Ingredients</button>}</div></details>)}</div>
    </div>
   </section>
   <ClinicianReviews/>
   {page==='home'?<Raw html={data.outro}/>:<><Raw html={productPages[kind]||''}/><Raw html={socialSection}/><Raw html={pages.footer}/></>}</>}
  </main>
  {!offerHidden&&<div className="j-offer-control"><button className="j-offer-tab" onClick={()=>{setOffer(true);setOfferStep(0)}}>GET 10% OFF</button><button className="j-offer-dismiss" aria-label="Hide offer tab" onClick={()=>setOfferHidden(true)}>×</button></div>}
  {notice&&<div className="j-toast" role="status">{notice}</div>}
  {(drawer||modal||offer)&&<div className={"j-backdrop"+(offer?" j-offer-backdrop":"")+(modal?.gallery?" j-gallery-backdrop":"")} onClick={dismiss}>
   <div ref={dialogRef} role="dialog" aria-modal="true" aria-label={drawer?'Your cart':offer?'Get 10% off':modal?.title} className={drawer?'j-drawer j-cart-drawer'+(cart.length?'':' is-empty'):offer?'j-dialog j-offer':modal?.gallery?'j-dialog j-gallery-dialog':modal?.account?'j-dialog j-account-dialog':modal?.reviewPhotos?'j-dialog j-review-dialog':modal?.reviewForm?'j-dialog j-write-dialog':'j-dialog'} onClick={e=>e.stopPropagation()}>
    <button className="j-close" aria-label="Close dialog" onClick={dismiss}>{drawer?<img src={cart.length?"/assets/cart-close.svg":"/assets/cart-empty-close.svg"} alt=""/>: modal?.gallery?<img src="/assets/cart-empty-close.svg" alt=""/>:"×"}</button>
    {drawer?<CartContents cart={cart} setCart={setCart} shop={(key,selectedPack,selectedMode)=>{if(selectedPack!==undefined)setPack(selectedPack);if(selectedMode)setMode(selectedMode);shop(key)}} discount={discount} checkout={()=>{setDrawer(false);navigate('/checkout')}}/>:
     modal?.reviewPhotos?<ReviewPhotos records={modal.reviewPhotos} initial={modal.index}/>:modal?.reviewForm?<ReviewForm kind={modal.reviewForm}/>:modal?.account?<AccountPanel signIn={()=>navigate('/account/login')}/>:offer?<div className="j-offer-content"><img className="j-offer-logo" src={media.logo} alt="JIYU"/>{offerStep===0?<><h2>Claim Your<br/><em>10% Off</em></h2><p>What’s your skin been asking for lately?</p>{['Blemish Control & Clarity','Deep Moisture & Hydration','Smoothing & Radiance','Soothing & Redness Relief','Firming & Fine Line Support'].map(t=><Button key={t} onClick={()=>setOfferStep(1)}>{t}</Button>)}<button className="j-no-thanks" onClick={dismiss}>No thanks</button></>:offerStep===1?<><h2>You’ve Got<br/><em>10% Off</em></h2><Button onClick={()=>setOfferStep(2)}>CONTINUE</Button><button className="j-no-thanks" onClick={dismiss}>No thanks</button></>:offerStep===2?<form onSubmit={e=>{e.preventDefault();setDiscount(true);localStorage.setItem('jiyu-discount','true');setOfferStep(3)}}><h2>Unlock Your<br/><em>10% Off</em></h2><label className="visually-hidden" htmlFor="offer-email">Email address</label><input id="offer-email" aria-label="Email for offer" type="email" placeholder="Your email address" required/><Button>GET MY CODE</Button><small>Your email stays in this demo and is not submitted.</small><button type="button" className="j-no-thanks" onClick={()=>setOfferStep(1)}>Back</button></form>:<><h2>Your Code<br/><em>Is Ready</em></h2><strong className="j-code">GLOW10</strong><p>10% off has been applied to your bag.</p><Button onClick={()=>shop()}>SHOP NOW</Button></>}</div>:

     <><h2 className={modal.gallery?"visually-hidden":undefined}>{modal.title}</h2>{modal.image&&!modal.video&&<><img className="j-modal-image" src={modal.image} alt={modal.title}/></>} {modal.video&&<Video src={modal.video} poster={modal.image}/>} {modal.text&&<p>{modal.text}</p>}{modal.cta&&<Button onClick={()=>shop()}>SHOP THE ROUTINE</Button>}{modal.link&&<a href={modal.link} target="_blank" rel="noreferrer">Read on the original JIYU website</a>}{modal.privacySettings&&<form onSubmit={e=>{e.preventDefault();setModal({title:'Preferences saved',text:'Your preferences have been saved for this preview only.'})}}><p>Choose your privacy preferences.</p><label><input type="checkbox" defaultChecked disabled/> Essential cookies</label><label><input type="checkbox"/> Analytics</label><label><input type="checkbox"/> Marketing</label><Button>SAVE PREFERENCES</Button></form>}{modal.loyalty&&<><p>Sign in or create your Unfiltered Society account.</p><form className="j-loyalty-form" onSubmit={e=>{e.preventDefault();setModal({title:'Welcome to Unfiltered Society',text:'Your assignment account preview is ready. Explore rewards and member benefits here.',cta:true})}}><label>Email<input type="email" aria-label="Account email" required placeholder="Your email address"/></label><Button>SIGN IN OR SIGN UP</Button><small>Assignment preview — no account is created or personal information sent.</small></form></>}{modal.checkout&&<><p>Your order preview includes {totalQty} item{totalQty===1?'':'s'}.</p><div className="j-total"><span>Order total</span><strong>{money(total-discountAmount)}</strong></div><p>This is an assignment checkout preview. No order is placed and no payment details are collected.</p><Button onClick={dismiss}>CONTINUE EXPLORING</Button></>}</>}
   </div></div>}
 </>
}
