import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
const origin='https://app.thefrontrowhealth.com';
export default function ClinicianSticker({kind,visible,quant=false}){
 const frame=useRef(null),dialog=useRef(null),wrapper=useRef(null),closeRef=useRef(null);const [scale,setScale]=useState(quant?1:.72),[height,setHeight]=useState(113),[min,setMin]=useState(false),[stack,setStack]=useState([]);const active=stack.at(-1),id=kind==='toner'?5434:5435,widget=quant?(kind==='toner'?9812:9814):(kind==='toner'?9813:9815),presentation=quant?'quant':'sticker';
 useEffect(()=>{const resize=()=>{if(quant)return;const z=Math.min(1,(wrapper.current?.parentElement.querySelector('.swiper-slide')?.clientWidth||350)*.9/437);setScale(z);frame.current?.contentWindow?.postMessage({name:'STICKER_RESIZED',data:{zoom:z}},origin)};const observer=new ResizeObserver(resize);if(wrapper.current)observer.observe(wrapper.current);function message(e){if(e.origin!==origin||![frame.current?.contentWindow,dialog.current?.contentWindow].includes(e.source))return;if(['STICKER_REQUEST_READY_STATUS','QUANT_REQUEST_READY_STATUS'].includes(e.data?.name)){e.source.postMessage({name:'PARENT_READY'},origin);resize()}else if(quant&&e.data?.name==='RESIZE_HEIGHT')setHeight(Math.max(80,Math.min(400,Number(e.data.value)||113)));else if(e.data?.name==='RESIZE_STICKER')resize();else if(e.data==='TOGGLE_STICKER')setMin(v=>!v);else if(['OPEN_MODAL_STICKER','OPEN_MODAL'].includes(e.data))setStack([{type:'reviews'}]);else if(e.data==='SCROLL_TO_TESTIMONIALS')document.querySelector('.j-clinician-reviews')?.scrollIntoView({behavior:'smooth'});else if(e.data?.name==='OPEN_TESTIMONIALS_MODAL')setStack([{type:'testimonials',message:{name:'SCROLL_TO_REVIEW',value:e.data.value}}]);else if(['OPEN_PROVIDER_MODAL','OPEN_PROVIDER_MODAL_FROM_TESTIMONIALS'].includes(e.data?.name))setStack(s=>[...s,{type:'profile',data:e.data.data}]);else if(e.data==='CLOSE_ALL_MODALS')setStack([]);else if(typeof e.data==='string'&&e.data.startsWith('CLOSE'))setStack(s=>s.slice(0,-1))}window.addEventListener('message',message);return()=>{observer.disconnect();window.removeEventListener('message',message)}},[kind,quant]);
 useEffect(()=>{if(!active)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';closeRef.current?.focus();const key=e=>{if(e.key==='Escape'){e.stopPropagation();setStack(s=>s.slice(0,-1))}};window.addEventListener('keydown',key,true);return()=>{document.body.style.overflow=before;window.removeEventListener('keydown',key,true);frame.current?.focus()}},[active]);
 return <><div ref={wrapper} className={quant?"j-clinician-quant":"j-clinician-sticker"} hidden={!visible}><iframe ref={frame} title="Clinicians’ Choice" src={`${origin}/api/widgets?presentation_type=${presentation}&product_id=${id}`} style={{width:quant?"100%":min?40:437,height:quant?height:78,transform:`scale(${scale})`}} onLoad={()=>frame.current?.contentWindow?.postMessage({name:'PARENT_READY'},origin)}/></div>{active&&createPortal(<div className="j-clinician-modal" role="dialog" aria-modal="true" aria-label="Clinicians’ Choice details"><button ref={closeRef} className="j-clinician-modal-close" aria-label="Close clinician badge details" onClick={()=>setStack(s=>s.slice(0,-1))}>×</button><iframe ref={dialog} key={active.type} title={active.type==='profile'?'Clinician profile':'Clinicians’ Choice details'} src={active.type==='profile'?`${origin}/api/widgets/v1/provider_profiles?widget_id=${widget}`:active.type==='testimonials'?`${origin}/api/widgets/testimonials?presentation_type=qual&product_id=${id}`:`${origin}/api/widgets/modal?presentation_type=${presentation}&product_id=${id}`} onLoad={()=>{if(active.data)dialog.current?.contentWindow?.postMessage({name:'OPEN',data:active.data},origin);if(active.message)dialog.current?.contentWindow?.postMessage(active.message,origin)}}/></div>,document.body)}</>;
}
