import React,{useEffect,useRef} from 'react';
import ClinicianSticker from './ClinicianSticker.jsx';
import Swiper from 'swiper';
import {A11y,Keyboard} from 'swiper/modules';
export default function ProductGallery({gallery,title,kind,photo,setPhoto,open,mobile}){
 const track=useRef(null),slider=useRef(null),thumbs=useRef(null);
 useEffect(()=>{const s=new Swiper(track.current,{modules:[A11y,Keyboard],a11y:{slideRole:'button',slideLabelMessage:'Enlarge product image {{index}}'},slidesPerView:1.055,spaceBetween:10,speed:400,keyboard:{enabled:true,onlyInViewport:true},on:{slideChange:sw=>setPhoto(sw.activeIndex)}});slider.current=s;return()=>{s.destroy();slider.current=null}},[kind]);
 useEffect(()=>{slider.current?.slideTo(photo);const t=thumbs.current?.children[photo];if(t){const row=thumbs.current;if(t.offsetLeft<row.scrollLeft||t.offsetLeft+t.offsetWidth>row.scrollLeft+row.clientWidth)row.scrollTo({left:t.offsetLeft,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'})}},[photo]);
 return <div className="j-gallery"><div className="j-image-grid">{gallery.map((src,i)=><button key={i} className={'j-grid-photo'+(i===2?' j-grid-photo-wide':'')} aria-label={'Enlarge '+title+' image '+(i+1)} onClick={()=>open(i)}><img src={src} alt={title+' — image '+(i+1)} loading={i<3?'eager':'lazy'}/></button>)}</div><div className="j-mobile-gallery"><div ref={track} className="swiper j-mobile-gallery-track"><div className="swiper-wrapper">{gallery.map((src,i)=><button key={i} className="swiper-slide j-main-photo" aria-label={'Enlarge product image '+(i+1)} onClick={()=>open(i)}><img src={src} alt={title+' — image '+(i+1)} loading={i<2?'eager':'lazy'}/></button>)}</div>{mobile&&<ClinicianSticker kind={kind} visible={photo===0}/>}</div><div ref={thumbs} className="j-thumbnails" aria-label="Product images">{gallery.map((src,i)=><button key={i} className={photo===i?'selected':''} onClick={()=>setPhoto(i)} aria-label={'View product image '+(i+1)} aria-current={photo===i?'true':undefined}><img src={src} alt="" loading="lazy"/></button>)}</div><span className="visually-hidden" aria-live="polite">Image {photo+1} of {gallery.length}</span></div></div>
}
