import filterHtml from './review-filter.json';
let reviews,photoReviews,pending;
export function initReviews(kind,open){let disposed=false,cleanup=()=>{};const roots=[...document.querySelectorAll('.jm-review-widget')];if(!roots.length)return cleanup;const observer=new IntersectionObserver(entries=>{if(!entries.some(e=>e.isIntersecting))return;observer.disconnect();pending??=Promise.all([import('./reviews-data.json'),import('./review-media.json')]);pending.then(([r,p])=>{if(disposed)return;reviews=r.default;photoReviews=p.default;cleanup=mountReviews(kind,open)}).catch(()=>{})},{rootMargin:'3000px'});roots.forEach(r=>observer.observe(r));return()=>{disposed=true;observer.disconnect();cleanup()}}

// Source snapshots stay local: filtering and votes never post to Judge.me.
function mountReviews(kind,open){
 const cleanups=[];
 document.querySelectorAll('.jm-review-widget').forEach((root,n)=>{
  const panel=root.closest('[data-jr-panel]')?.dataset.jrPanel;
  const product=panel?({tab_toner:'toner',tab_moisturizer:'cream',tab_bundle:'bundle'}[panel]||kind):kind;
  let store=false,rating=0,keyword='',sort='created_at',limit=15;const voted=new Map();
  const grid=root.querySelector('.jdgm-masonry-grid__container'),section=root.querySelector('.jdgm-masonry-grid'),more=root.querySelector('.jdgm-masonry-grid__btn')||Object.assign(document.createElement('button'),{className:'jdgm-masonry-grid__btn',type:'button',textContent:'Show more'});
  if(!grid)return;if(!more.isConnected||grid.contains(more))section.after(more);
  const status=document.createElement('p');status.className='j-review-status';status.setAttribute('role','status');section.after(status);
  const filters=document.createElement('div');filters.className='j-review-filters';filters.hidden=true;
  const keywords=[...root.querySelectorAll('.jm-keyword-sentiment__text')].map(x=>x.textContent.trim()).filter(Boolean);
  filters.innerHTML=filterHtml;filters.querySelectorAll('input[type=radio]').forEach(i=>{i.name=/^[1-5]$/.test(i.value)?'review-rating-'+n:'review-keyword-'+n});filters.querySelectorAll('input[name="review-keyword-'+n+'"]').forEach((input,i)=>{const word=keywords[i]||input.value;const label=input.closest('label');if(label){label.querySelector('span')?.replaceChildren(document.createTextNode(word))}input.value=word;input.id='review-keyword-'+n+'-'+i;if(label)label.htmlFor=input.id});filters.querySelector('.jm-filter-panel__clear-btn')?.removeAttribute('aria-hidden');
  const bar=root.querySelector('.jm-custom-answer-filter');root.querySelector('.jm-review-widget__body')?.before(filters);if(!filters.isConnected)grid.parentElement.before(filters);
  function items(){let rows=[...reviews[store?'store':product]];if(rating)rows=rows.filter(r=>r.rating===rating);if(keyword)rows=rows.filter(r=>r.text.toLowerCase().includes(keyword.toLowerCase()));if(sort==='highest_rating')rows.sort((a,b)=>b.rating-a.rating);else if(sort==='lowest_rating')rows.sort((a,b)=>a.rating-b.rating);else if(sort==='most_helpful')rows.sort((a,b)=>b.helpful-a.helpful);else if(sort==='with_pictures')rows=rows.filter(r=>r.images.length);else if(sort==='pictures_first'||sort==='videos_first')rows.sort((a,b)=>b.images.length-a.images.length);else rows.sort((a,b)=>new Date(b.date)-new Date(a.date));return rows}
  function render(){const rows=items();grid.innerHTML=rows.slice(0,limit).map(r=>`<div class="jdgm-masonry-grid__masonry-item" role="listitem" data-review-id="${r.id}">${r.html}</div>`).join('');section.style.maxHeight=limit===15?'1050px':'none';if(more){more.hidden=limit>=rows.length;more.textContent='Show more'}status.textContent=!rows.length?'No matching reviews in this assignment’s saved review sample.':limit>=rows.length?'All matching reviews in the saved sample are shown.':'';grid.querySelectorAll('.jm-voting-controls__button').forEach(b=>{const id=b.closest('[data-review-id]').dataset.reviewId;if(voted.get(id)===b.getAttribute('aria-label')){b.setAttribute('aria-pressed','true');const count=b.querySelector('.jm-text');if(count)count.textContent=String(Number(count.textContent)+1)}});grid.querySelectorAll('.jdgm-review-card__more-text').forEach(el=>{el.tabIndex=0;el.setAttribute('role','button')});grid.querySelectorAll('img').forEach(img=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label','Open customer review photo')})}
  function click(e){const t=e.target.closest('button,a,[role="tab"],[role="button"],img');if(!t)return;
   if(t.matches('.jm-custom-answer-filter')){filters.hidden=!filters.hidden;t.setAttribute('aria-expanded',String(!filters.hidden));return}
   if(t.matches('[data-clear-review],.jm-filter-panel__clear-btn')){rating=0;keyword='';filters.querySelectorAll('input').forEach(i=>{i.checked=false;if(i.type==='search')i.value=''});limit=15;render();return}
   if(t.matches('.jdgm-tab')){e.preventDefault();store=t.textContent.toLowerCase().includes('store');root.querySelectorAll('.jdgm-tab').forEach(b=>{b.setAttribute('aria-selected',String(b===t));b.classList.toggle('jdgm-tab--active',b===t)});rating=0;limit=15;render();return}
   if(t.matches('.jdgm-masonry-grid__btn')){e.preventDefault();limit+=15;render();return}
   if(t.matches('.jm-action-buttons__button')){e.preventDefault();open({title:'Write a review',reviewForm:product});return}
   if(t.matches('.jm-voting-controls__button')){const item=t.closest('[data-review-id]');if(!item)return;const id=item.dataset.reviewId,choice=t.getAttribute('aria-label');if(voted.get(id)===choice)voted.delete(id);else voted.set(id,choice);render();return}
   if(t.matches('.jm-media-grid__arrow')){const rail=t.parentElement.querySelector('.jm-media-grid__container')||t.parentElement.querySelector('[role="list"]');rail?.scrollBy({left:t.className.includes('next')?240:-240,behavior:'smooth'});return}
   const thumbnail=t.closest('.jm-media-grid__item');if(thumbnail){const buttons=[...thumbnail.parentElement.querySelectorAll('.jm-media-grid__item')],index=buttons.indexOf(thumbnail);const records=photoReviews[product]||[];if(records.length)open({title:'Customer review photos',reviewPhotos:records,index:Math.min(index,records.length-1)});return}
   if(t.tagName==='IMG'&&t.closest('[data-review-id]')){const record=reviews[store?'store':product].find(r=>r.id===t.closest('[data-review-id]').dataset.reviewId);open({title:'Customer review photo',reviewPhotos:record.images.map(image=>({image,html:record.html})),index:Math.max(0,record.images.indexOf(t.getAttribute('src')))});return}
   if(t.matches('.jm-review-content__read-more,.jdgm-review-card__read-more,.jdgm-review-card__more-text')){const wrapper=t.closest('.jdgm-review-card');wrapper.classList.toggle('j-review-expanded');t.textContent=wrapper.classList.contains('j-review-expanded')?'Show less':'Show more'}
  }
  function change(e){if(e.target.matches('.jm-sort-filter__select'))sort=e.target.value;else if(e.target.matches('.jdgm-tab-dropdown__select'))store=e.target.value.includes('store');else if(e.target.name===`review-rating-${n}`)rating=Number(e.target.value);else if(e.target.name===`review-keyword-${n}`)keyword=e.target.value;else if(e.target.closest('.jm-keyword-sentiment')||e.target.matches('[id^=tag-keyword-filter]'))keyword=e.target.checked?e.target.value:'';else if(e.target.matches('.j-review-search input'))keyword=e.target.value;else return;limit=15;render()}
  function key(e){if(e.key==='Enter'&&e.target.matches('img[role="button"],.jdgm-review-card__more-text'))e.target.click()}
  root.addEventListener('click',click);root.addEventListener('change',change);root.addEventListener('input',change);root.addEventListener('keydown',key);render();cleanups.push(()=>{root.removeEventListener('click',click);root.removeEventListener('change',change);root.removeEventListener('input',change);root.removeEventListener('keydown',key);filters.remove();status.remove()});
 });return()=>cleanups.forEach(f=>f());
}
